# Site settings
title: Crypto Cabochon
description: Crypto Art Collectibles
keywords: cryptocabochon, cryptoart, zcash, bch, ada, cardano
author: nighthawk24
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.cryptocabochon.com" # the base hostname & protocol for your site
